services:
  - type: web
    name: 6ixkar-ml-service
    env: python
    region: oregon
    buildCommand: "cd python-ml-service && pip install -r requirements.txt"
    startCommand: "cd python-ml-service && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
